# Generated by Django 2.1.5 on 2019-02-04 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Website Down', 'Website Down'), ('Problem with WiFi', 'Problem with WiFi'), ('Server Down', 'Server Down'), ('Cannot Login', 'Cannot Login'), ('Critical Bug', 'Critical Bug'), ('Problem with Billing System', 'Problem with Billing System')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.PositiveIntegerField(choices=[(1, 4), (2, 24), (3, 72), (4, 168), (5, 720)], default=3)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('In Process', 'In Process'), ('Resolved', 'Resolved'), ('Cancelled', 'Cancelled')], default='Issued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry', models.DateTimeField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.Vendor'),
        ),
    ]
