# Generated by Django 2.1.5 on 2019-02-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Website Down', 'Website Down'), ('Problem with WiFi', 'Problem with WiFi'), ('Server Down', 'Server Down'), ('Cannot Login', 'Cannot Login'), ('Critical Bug', 'Critical Bug'), ('Problem with Billing System', 'Problem with Billing System')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.PositiveIntegerField(choices=[(4, 1), (24, 2), (72, 3), (168, 4), (720, 5)]),
        ),
    ]
