# Generated by Django 2.1.5 on 2019-02-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20190205_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
